name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening an issue in NetworkPoll, the maintainer will get back to you soon."
        pr-message: "Thank you for creating a pull request on NetworkPoll, the maintainer will get back to you soon."
